DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `fname` varchar(30) COLLATE utf8_bin NOT NULL,
  `lname` varchar(30) COLLATE utf8_bin NOT NULL,
  `email` varchar(255) COLLATE utf8_bin NOT NULL,
  `old_email` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `username` varchar(50) COLLATE utf8_bin NOT NULL,
  `last_email_change` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `twofactor_secret` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `emailverify_secret` varchar(128) COLLATE utf8_bin DEFAULT NULL,
  `password_hash` varchar(72) COLLATE utf8_bin DEFAULT NULL,
  `passwordchange_secret` varchar(128) COLLATE utf8_bin DEFAULT NULL,
  `last_password_change` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `login_attempts` tinyint unsigned DEFAULT '0',
  `last_login` timestamp NULL DEFAULT NULL,
  `disabled` tinyint NOT NULL DEFAULT '0',
  `disable_secret` varchar(128) COLLATE utf8_bin DEFAULT NULL,
  `verified` tinyint NOT NULL DEFAULT '0',
  `external_type` varchar(8) COLLATE utf8_bin DEFAULT NULL,
  `external_id` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_UNIQUE` (`email`),
  UNIQUE KEY `username_UNIQUE` (`username`),
  UNIQUE KEY `external_id_UNIQUE` (`external_id`),
  UNIQUE KEY `emailverify_secret_UNIQUE` (`emailverify_secret`),
  UNIQUE KEY `twofactor_secret_UNIQUE` (`twofactor_secret`),
  UNIQUE KEY `disable_secret_UNIQUE` (`disable_secret`),
  UNIQUE KEY `old_email_UNIQUE` (`old_email`),
  UNIQUE KEY `passwordchange_secret_UNIQUE` (`passwordchange_secret`)
) ENGINE=InnoDB AUTO_INCREMENT=387 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;